import uuid

from django.conf import settings
from django.db import models

from monitoring.models import Intersection


class Notification(models.Model):
    """
    An alert generated by the system (congestion spike, accident,
    signal failure, emergency vehicle en route, etc.) and pushed to
    connected dashboard clients over the `notifications` WebSocket
    group. Persisted here too so the notification center has history.
    """

    class Category(models.TextChoices):
        CONGESTION = 'congestion', 'Congestion Alert'
        ACCIDENT = 'accident', 'Accident'
        SIGNAL_FAILURE = 'signal_failure', 'Signal Failure'
        EMERGENCY_VEHICLE = 'emergency_vehicle', 'Emergency Vehicle'
        CAMERA_OFFLINE = 'camera_offline', 'Camera Offline'
        SYSTEM = 'system', 'System'

    class Priority(models.TextChoices):
        LOW = 'low', 'Low'
        MEDIUM = 'medium', 'Medium'
        HIGH = 'high', 'High'
        CRITICAL = 'critical', 'Critical'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    intersection = models.ForeignKey(
        Intersection, on_delete=models.CASCADE, null=True, blank=True, related_name='notifications'
    )
    category = models.CharField(max_length=30, choices=Category.choices)
    priority = models.CharField(max_length=10, choices=Priority.choices, default=Priority.MEDIUM)
    title = models.CharField(max_length=200)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    recipients = models.ManyToManyField(
        settings.AUTH_USER_MODEL, blank=True, related_name='notifications',
        help_text='Empty = broadcast to all connected operators'
    )
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        db_table = 'notifications'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['category']),
            models.Index(fields=['priority']),
            models.Index(fields=['is_read']),
        ]

    def __str__(self):
        return f'[{self.priority}] {self.title}'
