# Generated by Django 5.0.6 on 2026-07-30 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Human-readable address / area', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'intersections',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status'], name='intersectio_status_af1e4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('camera_url', models.CharField(help_text='RTSP/HTTP stream URL consumed by the CV worker', max_length=500)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('resolution', models.CharField(blank=True, help_text='e.g. 1920x1080', max_length=20)),
                ('fps', models.PositiveSmallIntegerField(default=15)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='monitoring.intersection')),
            ],
            options={
                'db_table': 'cameras',
            },
        ),
        migrations.CreateModel(
            name='TrafficDensitySnapshot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_count', models.PositiveIntegerField(default=0)),
                ('queue_length_meters', models.FloatField(default=0)),
                ('avg_waiting_time_seconds', models.FloatField(default=0)),
                ('congestion_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], default='low', max_length=20)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='density_snapshots', to='monitoring.intersection')),
            ],
            options={
                'db_table': 'traffic_density_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('bus', 'Bus'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('ambulance', 'Ambulance'), ('police', 'Police Vehicle'), ('other', 'Other')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='YOLOv8 detection confidence, 0-1')),
                ('is_emergency', models.BooleanField(default=False)),
                ('bounding_box', models.JSONField(blank=True, help_text='[x_min, y_min, x_max, y_max] in frame pixels', null=True)),
                ('speed_kmph', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detections', to='monitoring.camera')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detections', to='monitoring.intersection')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status'], name='cameras_status_3e06fd_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficdensitysnapshot',
            index=models.Index(fields=['intersection', 'captured_at'], name='traffic_den_interse_7fca33_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['intersection', 'timestamp'], name='vehicles_interse_8b14f8_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_type'], name='vehicles_vehicle_d54349_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_emergency'], name='vehicles_is_emer_87b77c_idx'),
        ),
    ]
