# Generated by Django 6.0.7 on 2026-07-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carbon_emission', models.FloatField(help_text='Estimated carbon emission in grams')),
                ('fuel_consumption', models.FloatField(help_text='Estimated fuel consumption in liters')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='monitoring.intersection')),
            ],
        ),
    ]
