# Generated by Django 5.0.6 on 2026-07-30 13:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('green_time', models.PositiveSmallIntegerField(help_text='seconds')),
                ('yellow_time', models.PositiveSmallIntegerField(default=3, help_text='seconds')),
                ('red_time', models.PositiveSmallIntegerField(help_text='seconds')),
                ('mode', models.CharField(choices=[('fixed', 'Fixed Timing'), ('dynamic', 'AI-Optimized'), ('manual', 'Manual Override'), ('emergency', 'Emergency Priority')], default='fixed', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated_by', models.CharField(default='system', help_text="'system' (AI) or operator username", max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='monitoring.intersection')),
            ],
            options={
                'db_table': 'signals',
            },
        ),
        migrations.CreateModel(
            name='SignalChangeLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_green_time', models.PositiveSmallIntegerField()),
                ('new_green_time', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('triggered_by', models.CharField(default='system', max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='signals_app.signal')),
            ],
            options={
                'db_table': 'signal_change_logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
