# Generated by Django 5.0.6 on 2026-07-30 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_cards', models.JSONField(default=list, help_text="e.g. ['active_intersections','total_vehicles','congestion','emissions']")),
                ('refresh_interval_seconds', models.PositiveSmallIntegerField(default=10)),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.intersection')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_preferences',
            },
        ),
    ]
