# Generated by Django 6.0.7 on 2026-07-30 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_time', models.IntegerField(default=30, help_text='Time in seconds')),
                ('yellow_time', models.IntegerField(default=5, help_text='Time in seconds')),
                ('red_time', models.IntegerField(default=30, help_text='Time in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='monitoring.intersection')),
            ],
        ),
    ]
