# Generated by Django 5.0.6 on 2026-07-30 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('carbon_emission_kg', models.FloatField(help_text='Estimated CO2 in kilograms')),
                ('fuel_consumption_liters', models.FloatField(help_text='Estimated fuel burned in liters')),
                ('pollution_index', models.FloatField(blank=True, help_text='Composite air-quality proxy score', null=True)),
                ('idle_time_seconds', models.FloatField(default=0, help_text='Aggregate vehicle idle time')),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='monitoring.intersection')),
            ],
            options={
                'db_table': 'emissions',
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['intersection', 'window_start'], name='emissions_interse_3f0d06_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficStatistic',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('total_vehicles', models.PositiveIntegerField(default=0)),
                ('avg_congestion_score', models.FloatField(default=0)),
                ('avg_waiting_time_seconds', models.FloatField(default=0)),
                ('peak_hour', models.PositiveSmallIntegerField(blank=True, help_text='0-23', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='monitoring.intersection')),
            ],
            options={
                'db_table': 'traffic_statistics',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['intersection', 'period', 'period_start'], name='traffic_sta_interse_4addef_idx')],
                'unique_together': {('intersection', 'period', 'period_start')},
            },
        ),
    ]
